### ISSUE TITLE
Add dislike

### ISSUE THREAD

**Issue by VictorSF1** [cat-in-136/redmine_hearts#31]
Hi,
Is it possible to expand the plugin's capabilities so that there is one more button and dislikes are taken into account?

**Comment by cat-in-136** [comment]
Technically possible but I have no plan to support.

I recommend following plugin:
 * If you want positive(+1)/negative(-1) voting system:
   * https://github.com/ojde/redmine-vote_on_issues-plugin
 * If you want "Reaction" with some different icons
   * https://github.com/happy-se-life/like
     * Note that: need to modify code to change icons
